# Generated by Django 3.2.13 on 2022-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('artist', models.CharField(max_length=40)),
                ('audio', models.FileField(upload_to='audio')),
                ('cover', models.ImageField(upload_to='images')),
            ],
        ),
    ]
